burger/urls.py
from django.urls import path

from . import views

app_name = 'burger'

urlpatterns = [
    path('', views.index, name='index'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
]

pizza/urls.py
from django.urls import path

from . import views

app_name = 'pizza'

urlpatterns = [
    path('', views.index, name='index'),
]

register/urls.py
from django.urls import path

from . import views

app_name = 'register'

urlpatterns = [
    path('', views.index, name='index'),
]

sanni/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls', namespace="dashboard")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^burger/', include('burger.urls', namespace="burger")),
    url(r'^pizza/', include('pizza.urls', namespace="pizza"))

]

burger/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

pizza/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

burger/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'burger/burger.html')

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'dashboard/dashboard.html')

login/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'login/login.html')

pizza/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pizza/pizza.html')

register/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'register/register.html')

burger/templates/burger/burger.html
{% extends 'base.html'%} {%load static%}

{% block styling %}
<link rel="stylesheet" href="{% static 'css/burger.css' %}" />
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="bigburger">
        <img style="width: 573px;height: 344px; margin-top:25px; margin-left:180px;"
            src="https://media.discordapp.net/attachments/767045716420853772/768334576212246538/yesburger.jpg">
        <div class="title">
            <p>Sanni's Hamburger</p>
            <p style="font-size: 18px;">We serve the best burger in town.</p>
        </div>
    </div>
    <div class="garis">
        <h2>OUR MENU<h2>
    </div>
    <div class="container-menu">
        <img style="width: 350px;height: 250px;"
            src="https://media.discordapp.net/attachments/767045716420853772/770258785381253120/beef.png?width=678&height=452">
        <img style="width: 350px;height: 250px;margin-left: 146px;"
            src="https://media.discordapp.net/attachments/767045716420853772/770258788921376788/chicken.png?width=678&height=452">
        <img style="width: 350px;height: 250px;"
            src="https://media.discordapp.net/attachments/767045716420853772/770258799264268358/veggie.png?width=677&height=452">
        <img style="width: 350px;height: 250px;margin-left: 146px;"
            src="https://media.discordapp.net/attachments/767045716420853772/770258794151542814/fishie.png?width=678&height=452">
    </div>
    <div class="garis">
        <h2>Additional Toppings</h2>
        <div class="topping">
            <div class="isi">
                <div class="tambah">
                <p style="width: 262px;">Mozarella Cheese<br>Rp.10.000</p>
                <p style="width: 262px;">Double Cheddar Cheese<br>Rp.7.000</p>
                </div>
                <div class="tambah">
                <p style="width: 262px;">Add-On Beef Patty<br>Rp.10.000</p>
                <p style="width: 262px;">Add-On Chicken Patty<br>Rp.10.000</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html'%} {%load static%}

{% block styling %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
<link href="css/bootstrap.css" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active" style="width: 100vw; height: 88vh;">
                <img style="width: 100vw; max-height: 110vh;"
                    src="https://thumbor.thedailymeal.com/7zfIDkh61JrdMi5-0uZX9B3_miY=//https://www.thedailymeal.com/sites/default/files/2017/06/12/0000000BurgerHEROIMAGEshutterstock.jpg"
                    alt="3 Burgers">
            </div>

            <div class="item" style="width: 100vw; height: 88vh;">
                <img style="width: 100%;"
                    src="https://subwallpaper.com/Widescreen-Wallpapers/cheese-pizza-wallpaper-1080p-For-Widescreen-Wallpaper.jpg"
                    alt="Cheese Pizza">
            </div>

            <div class="item" style="width: 100vw; height: 88vh;">
                <img style="width: 100%; max-height: 100vh;"
                    src="https://s1.1zoom.me/b5050/648/Hamburger_French_fries_Knife_Vegetables_Beer_Black_540436_3840x2400.jpg"
                    alt="Burger and Cola">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
{% endblock %}

login/templates/login/login.html
{% extends 'base.html'%} {%load static%}

{% block styling %}
<link rel="stylesheet" href="{% static 'css/login.css' %}" />
{% endblock %}

{% block content %}

<div class="container">
    <div class="login" style="margin-left : 800px;">
        <div class="logo">
            <img class="logoimg"
                src="https://media.discordapp.net/attachments/651415548965421086/768396585121611776/IMG-8527.PNG?width=369&height=369">
            <h3 style="font-family: roboto; font-weight: 1000; width: fit-content; margin: auto; margin-top: 20px; font-size: 25px;">LOGIN</h3>
        </div>
        <div class="input" style="border-radius: 25px">
            <form>
                <div class="isian">
                    <input class="baris1" type="text" placeholder="Username or Email" style="border-radius: 25px">
                    <input class="baris1" type="password" placeholder="Password" style="border-radius: 25px">
                </div>
                <div class="signup">
                    <button class="bt_signup"> Login </button>
                </div>
                <div class="register">
                    <p> Don't have an account? </p>
                    <a href="{% url 'register:index' %}">
                        <p style="margin-left: 5px; color: rgb(35, 120, 233);"> Register</p>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

pizza/templates/pizza/pizza.html
{% extends 'base.html'%} {%load static%}

{% block styling %}
    <link rel="stylesheet" href="{% static 'css/pizza.css' %}" />
{% endblock %}

{% block content %}
    
    <div class="container-fluid">
        <div class="line"></div>
        <div class ="burgerbig"></div>
        <div class = "title"style="margin-left: 15px;">
            <p>Sanni's Pizza</p>
        </div>
        <div class ="subtitle">
            <p>Get a taste of our delicious pizzas</p> 
        </div>
    <div class ="bigburger">
        <img style="width: 603px;height: 374px; margin-top:250px; margin-left:220px;"
        src="https://media.discordapp.net/attachments/767045716420853772/770509270097068052/bigpizza.png?width=672&height=452">
    </div>
    <div>
    <div class="garis1" style="margin-top: 50px;"> </div>
    <div class ="garis2" style="margin-top:50px;"> </div>
    <div class ="menu"style="margin-top: 50px;">OUR MENU</div></div>
   
    <div class ="container-menu" style="margin-top: 80px; margin-left:250px;" >
    <div>
        <img style="width: 350px;height: 250px;margin-top :10px"
        src="https://media.discordapp.net/attachments/767045716420853772/770519948363038730/pizza1.png?width=678&height=452">
    </div>
    <div>
        <img style="width: 350px;height: 250px;margin-top :10px"
        src="https://media.discordapp.net/attachments/767045716420853772/770519960664539146/pizza2.png?width=678&height=452">
        
    </div>
    <div>
        <img style="width: 350px;height: 250px;margin-top :40px"
        src="https://media.discordapp.net/attachments/767045716420853772/770519962522484736/pizza3.png?width=679&height=452">
    </div>
    <div>
        <img style="width: 350px;height: 250px;margin-top :40px"
        src="https://media.discordapp.net/attachments/767045716420853772/770519966033641483/pizza4.png?width=677&height=452">
    </div>
    </div>
    <div>
        <div class="garis1" style="margin-top: 800px;">
            <div class="p"><p style="margin-top :90px;text-align:center;">Mozarella Crust<br>Rp.20.000</p></div>
            <div class="p"><p style="margin-top :115px;text-align:center;">Double Cheddar Cheese<br>Rp.15.000</p></div></div>
        <div class ="garis2" style="margin-top:800px;"> 
        <div class="p"><p style="margin-top :90px;text-align:center;">Thin-Crusty<br>Rp.10.000</p></div>
        <div class="p"><p style="margin-top :115px;text-align:center;">Extra Pepperoni<br>Rp.20.000</p></div>
    </div>
        <div class ="menu"style="margin-top:800px;">Additional Toppings</div></div>
       
</div>
{% endblock %}

register/templates/register/register.html
{% extends 'base.html'%} {%load static%}

{% block styling %}
<link rel="stylesheet" href="{% static 'css/register.css' %}" />
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="register">
        <div class="sanni">
            <img class="logoimg"
                src="https://media.discordapp.net/attachments/651415548965421086/768396585121611776/IMG-8527.PNG?width=369&height=369">
        </div>
        <div class="input">
            <form>
                <div class="isian">
                    <h3 style="font-family: roboto; font-weight: 1000; width: fit-content; margin: auto; font-size: 25px;" >CREATE ACCOUNT</h3> <br>
                    <input class="baris1" type="text" placeholder="Name">
                    <input class="baris1" type="text" placeholder="Email">
                    <input class="baris1" type="password" placeholder="Password">
                    <input class="baris1" type="password" placeholder="Confirm Password">
                </div>
                <div class="signup">
                    <button class="bt_signup"> Sign Up </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="css/bootstrap.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Leckerli+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  {% block styling %} {% endblock %}

  <style>
    a{
      color: black;
    }
    #navbarSupportedContent a:hover{
      color: black;
    }
    #loginBtn {
      border: 1px solid black !important;
    }
  </style>
</head>

<body>
  <nav style="background-color: #fefefe !important; padding: 0; justify-content: space-between; margin-bottom : -10px"
    class="navbar navbar-expand-lg">
    <nav style="display: contents; padding: 0; justify-content: space-between; margin: 0;"
      class="navbar navbar-expand-lg">
      <div style="display: flex; flex-direction: row; margin-inline-end: auto;">

        <a style="padding: 0; margin: 0; margin-left: 80px;" class="navbar-brand" href="#">
          <img style=" width: 70px; height: 70px; margin: auto; display: flex; flex-direction: row;"
            src="https://media.discordapp.net/attachments/651415548965421086/768396585121611776/IMG-8527.PNG?width=369&height=369">
        </a>

        <nav class="navbar navbar-expand-lg" style="font-family:Roboto;font-size: large;margin-top:5px;">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
              </li> <br>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false" style="margin-left:20px;">
                  Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/burger/">Burgers</a>
                  <a class="dropdown-item" href="/pizza/">Pizza</a>
                  <a class="dropdown-item" href="/minuman/">Minuman</a>
                </div>
              </li> <br>
              <li class="nav-item">
                <a class="nav-link" href="#" style="margin-left:20px;">About</a>
              </li>
          </div>
      </div>
      <div style="width: fit-content; margin-right: 50px;" class="button">
        <a href="{% url 'login:index' %}">
          <button id="loginBtn" type="button" class="btn  btn-outline-dark">Login</button>
        </a>

      </div>
    </nav>
  </nav>
  {% block content %} {% endblock %}

</body>

</html>